---
# https://rancher.com/docs/k3s/latest/en/installation/install-options/server-config/
# https://github.com/PyratLabs/ansible-role-k3s

# (bool) Specify if a host (or host group) are part of the control plane
k3s_control_node: true

# (dict) k3s settings for all control-plane nodes
k3s_server:
  node-ip: "{{ ansible_host }},{{ host_ipv6 }}"
  tls-san:
    - k8s.velinga.home
  docker: false
  flannel-backend: "none" # This needs to be in quotes
  disable:
    - flannel
    - traefik
    - servicelb
    - metrics-server
    - local-storage
  disable-network-policy: true
  disable-cloud-controller: true
  write-kubeconfig-mode: "644"
  cluster-cidr: "10.244.0.0/16,fd24::/56"
  service-cidr: "10.96.0.0/16,fd96::/112"
  kubelet-arg:
    - "feature-gates=GracefulNodeShutdown=true"
    - "feature-gates=MixedProtocolLBService=true"
    - "feature-gates=EphemeralContainers=true"
    - "feature-gates=ReadWriteOncePod=true"
    - "max-pods=200"
  kube-controller-manager-arg:
    - "bind-address=0.0.0.0"
  kube-proxy-arg:
    - "metrics-bind-address=0.0.0.0"
    - "proxy-mode=ipvs"
    - "ipvs-strict-arp"
  kube-scheduler-arg:
    - "bind-address=0.0.0.0"
  etcd-expose-metrics: true
  kube-apiserver-arg:
    - "anonymous-auth=true"
