---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  CLUSTER_DIR: "{{.PROJECT_DIR}}/cluster"
  K0S_DIR: "{{.PROJECT_DIR}}/provision/k0s"
  TERRAFORM_DIR: "{{.PROJECT_DIR}}/provision/terraform"

env:
  KUBECONFIG: "{{.PROJECT_DIR}}/cluster/kubeconfig"

includes:
  flux: .taskfiles/flux.yml
  format: .taskfiles/format.yml
  k0s: .taskfiles/k0s.yml
  lint: .taskfiles/lint.yml
  pre-commit: .taskfiles/pre-commit.yml
  terraform: .taskfiles/terraform.yml

tasks:
  encrypt:
    desc: Encrypt a file with sops
    cmds:
      - sops --encrypt --in-place {{.CLI_ARGS}}

  decrypt:
    desc: Decrypt an file that was encrypted with sops
    cmds:
      - sops --decrypt --in-place {{.CLI_ARGS}}

  pwgen:
    desc: Generate random password
    cmds:
      - openssl rand -base64 {{.CLI_ARGS}}
