---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 10.21.1
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: cert-manager
      namespace: kube-system
    - name: metallb
      namespace: networking
  values:
    deployment:
      kind: Deployment
      replicas: 1
    service:
      enabled: true
      type: LoadBalancer
      loadBalancerIPs:
        - "${METALLB_TREAFIK_ADDR}"
        - "${METALLB_TREAFIK_ADDR_V6}"
      externalTrafficPolicy: Local
      ipFamilyPolicy: PreferDualStack
      ipFamilies:
        - "IPv4"
        - "IPv6"
      annotations:
        metallb.universe.tf/loadBalancerIPs: "${METALLB_TREAFIK_ADDR}, ${METALLB_TREAFIK_ADDR_V6}"
        metallb.universe.tf/allow-shared-ip: traefik
      spec:
        externalTrafficPolicy: Local
    logs:
      general:
        format: json
        level: DEBUG
      access:
        enabled: true
        format: json
    ingressClass:
      enabled: true
      isDefaultClass: true
      fallbackApiVersion: v1
    ingressRoute:
      dashboard:
        enabled: false
    globalArguments:
      - "--api.insecure=true"
      - "--serverstransport.insecureskipverify=true"
      - "--providers.kubernetesingress.ingressclass=traefik"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"
    additionalArguments:
      - "--providers.kubernetesingress.ingressendpoint.ip=${METALLB_TRAEFIK_ADDR}"
      - "--providers.kubernetesingress.ingressendpoint.ip=${METALLB_TRAEFIK_IPV6_ADDR}"
      - "--providers.kubernetesingress.allowexternalnameservices=true"
      - "--providers.kubernetescrd.allowexternalnameservices=true"
    ports:
      traefik:
        expose: true
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
          options: "default"
      metrics:
        port: 8082
        expose: true
        exposedPort: 8082
    tlsOptions:
      default:
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        cipherSuites:
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 # TLS 1.2
          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 # TLS 1.2
          - TLS_AES_256_GCM_SHA384 # TLS 1.3
          - TLS_CHACHA20_POLY1305_SHA256 # TLS 1.3
        curvePreferences:
          - CurveP521
          - CurveP384
        sniStrict: true
    pilot:
      enabled: false
    experimental:
      plugins:
        enabled: false
    resources:
      requests:
        memory: 100Mi
        cpu: 500m
      limits:
        memory: 500Mi
