---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: networking
  name: cloudflare-ddns
  labels:
    app: cloudflare-ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
        - name: cloudflare-ddns
          image: ghcr.io/hotio/cloudflareddns:latest
          env:
            - name: TZ
              value: "${CONFIG_TZ}"
            - name: DETECTION_MODE
              value: "whoami.cloudflare"
            - name: CF_APITOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflare-ddns
                  key: api-token
            - name: CF_ZONES
              valueFrom:
                secretKeyRef:
                  name: cloudflare-ddns
                  key: zones
            - name: CF_HOSTS
              valueFrom:
                secretKeyRef:
                  name: cloudflare-ddns
                  key: hosts
            - name: CF_RECORDTYPES
              valueFrom:
                secretKeyRef:
                  name: cloudflare-ddns
                  key: record-types
            # https://hotio.dev/containers/cloudflareddns/#log-levels
            - name: LOG_LEVEL
              value: '3'
            - name: INTERVAL
              value: '300'
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi