# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
# CLOUDFLARE_EMAIL: The email used to log into https://dash.cloudflare.com
# CLOUDFLARE_APIKEY: Top right corner, "My profile" > "Global API Key"
# CLOUDFLARE_ZONEID: Can be found in the "Overview" tab of your domain
# CLOUDFLARE_RECORD_NAME: The name of your A record
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ytSXR/ylamw40xsS0GEBpp54egOCwOsC,iv:0xj1VaTvIKH40g58UHsTXKMPVQ055rNWNzO6o4TnCg4=,tag:x3PWlHThi8dngQnWFGoL8A==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:f8wxy/hicPzyb2v3XSH3O1wXLTGeijU3ebC8SBQnI9Mp4z8xzQ==,iv:eR5csCiWHhbmuy+6rR9d7y5+k43VwNMiVyLrsNeXwlg=,tag:OvQizohllLLNk+4/yHgyMg==,type:str]
    CLOUDFLARE_ZONEID: ENC[AES256_GCM,data:Vube7wUoHrpn3Bzf0wQVkXQZfErdrAi2pGu6DScGQLM=,iv:0jblQRTUc74d6wC8Dt5e2HXzNt7/TalG5AYwTlLaYOI=,tag:epcShNUKDrL0t6SxX3dSLQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:Yi+o,iv:iB1SXX8OEGVfoqH4KmmbFzVp85jqk9+0JSi2JryrcCo=,tag:8ixZkMrlq0ScSsAXObAHSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yj38cqvxadheycx8tt5yxk8stt6l9cf5s3e6wd743752nr70d9zq99tna0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhN0FMeFUwUksvWVNyNFk3
            Sis1WVRMYmV0L2FSTlZnUWsyRzdkdy9XVVRjCjg0MGp0WkpyV1BRMzU5elJaVHZG
            UkY3NmZ1US8wYjZRMGw0N3NBL0hVR3cKLS0tIHkxdGNQSEZvRVRwZUxVMDJORSt2
            clRFUHJTblUxQmNDTWpzNGRXa1F6elkK76gEMaYY3M5tflQAYRlENr5W1I/3zNH9
            HVTfP+14v2RRXAegppErEt/LCBdgh6ifRSJAJX0e6Oc0ljY393/uVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-18T00:55:28Z"
    mac: ENC[AES256_GCM,data:21wYqMjT+1viOB0aLZUWEjzvZX9I2c5gVQ5qVrFI58g/qgGv5Ih31Nn+BVcDPS5PS/2WVhpFLek6Zev7cb7eVqUcFygFIyewCJXHWAXBp2kNaNn0UIxMdSXmrYN5V/+macaE/pYL5l14tHYHSGPD9UUEOHPwk81LpsKb+hYchEw=,iv:U/2JWeX4ty4pQRO/h/vKke/rFOJGPV9RNHX17OdYhZw=,tag:Zkxb9mETwh+EeAa+mnwBmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
