---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wikijs
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: wikijs
      version: 6.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/requarks/wiki
      tag: "2.5"

    env:
      TZ: "Europe/Amsterdam"
      DB_TYPE: postgres
      DB_HOST: wikijs-postgres.default.svc.cluster.local
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: ${SECRET_WIKIJS_POSTGRES_PASSWORD}
      DB_NAME: wikijs

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "wikipedia"
          hajimari.io/appName: "Wiki.js"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "wiki.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "wiki.${SECRET_DOMAIN}"
            secretName: "${SECRET_DOMAIN/./-}-tls"

    persistence:
      config:
        enabled: true
        existingClaim: wikijs-config
      data:
        enabled: true
        mountPath: /app/wiki/data
        existingClaim: wikijs-data
