---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres-configmap.yaml
  - postgres-secret.yaml
  - postgres-db.yaml
  - config-pvc.yaml
  - data-pvc.yaml
  - helm-release.yaml
