apiVersion: v1
kind: Secret
metadata:
    name: wikijs-postgres-secret
    namespace: default
type: Opaque
stringData:
    superUserPassword: ENC[AES256_GCM,data:9tBi85wNuD1a8ACQKXyUgtoIKxsbDn5G81OBJUA/taUbptmL58YcBDekYSE=,iv:nDSpBIbl+3a/1mMK6Vz0Zx/K1qS+lsgQyyyt9R5Pki0=,tag:ZlYFtTBO5gcxFuuF4gmwBA==,type:str]
    replicationUserPassword: ENC[AES256_GCM,data:Licj541Qzup7BhVEbYv2W6WoIoQj5/nPqTAei2Xdw4K4fWVyp7OaEQZ4rJE=,iv:BlM/ZAxC9PJRoYGOAluzKnzEP7pjtf7W2wH+Aly6wmM=,tag:QPQJU+AB9ht049Vx5tLCWA==,type:str]
    myDbPasword: ENC[AES256_GCM,data:qybKfxtjPeBya13qPV2vycmN/7IH9nO7J2P1gCm71/Uk83lmAIEz6QS4NRc=,iv:FXQv8riqntvMYFuEVFiceHgJkn6dYXcWB/7HEOL+DEk=,tag:2NfCg4UIUR3Ki+/XedgNyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yj38cqvxadheycx8tt5yxk8stt6l9cf5s3e6wd743752nr70d9zq99tna0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZb2RmUWVzRytJWmJWNzJP
            RlJyWHJESE5EbEZuTVpRUVBlR0o2TkJ0M2hRCmE5WlBmTHd1OGdnTkNUN0Nla0JU
            R0grWFc4VTBRQm5FeVFWUHZ0Y09aR1UKLS0tIExGVWIxQlhZejNJVmg3UlZRL3Q3
            dVBIcFdmUU93L0F3bmViL21wVDViOGsKKjGomqMPdCOd4iZzvX5qOnSDSfYhEcc8
            vpagH0j3T34Ux/ICQu7UBrnMckceRFrqVNXhhtvbROh1QaapEMXrfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-06T18:06:14Z"
    mac: ENC[AES256_GCM,data:9NG37v/EIhRS7pA308/jIR0Lke0ydr2KAn8ssUVsbRv0cK2XamGOcuAQddI7DuEw+vuQjX19gLosWJ+KE/fxpS6I4OlWCNsB6T7oFoJ7F5tbtTFU76o/u8YFPCJ5CJK9RGD07IjlGtLtaGbKJPZ8cdKrgGeOWCaqwts+iHZQ980=,iv:ZNQaOLCfCcMW525u8NsR2HGyL13IuKpfosNsdvQo4iU=,tag:8eCxBfG7isyEX87/HXtgMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
