---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mealie
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mealie
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: hkotel/mealie
      tag: v0.5.4
      pullPolicy: IfNotPresent

    env:
      TZ: "${CONFIG_TZ}"
      DEFAULT_EMAIL: david@${SECRET_DOMAIN}
      BASE_URL: https://meals.${SECRET_DOMAIN}

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "food"
          hajimari.io/appName: "Mealie"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "meals.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "${SECRET_DOMAIN/./-}-tls"
            hosts:
              - "meals.${SECRET_DOMAIN}"

    persistence:
      config:
        enabled: true
        storageClass: "ceph-block"
        accessMode: ReadWriteOnce
        size: 5Gi
