apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: ghost-cluster
spec:
  replicas: 1
  secretName: mysql-ghost-secret
  volumeSpec:
    persistentVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "ceph-block"
      resources:
        requests:
          storage: 1Gi