apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-pvc.yaml
  - helm-release.yaml
  - secret.sops.yaml
  - postgres-configmap.yaml
  - postgres-secret.yaml
  - postgres-db.yaml
