---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - error-pages.yaml
  - cloudflare-only.yaml
  - internal-only.yaml
  - authentik-forward-auth.yaml
  - rfc1918.yaml
  - redirect-path.yaml
  - internal-auth.yaml
  - external-auth.yaml
  - basic-auth.sops.yaml
  - basic-auth.yaml
