---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: mysql-operator-charts
  namespace: flux-system
spec:
  interval: 15m
  url: https://helm-charts.bitpoke.io
  timeout: 3m
