---
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: authentik-postgres
  namespace: security
spec:
  replicas: 1
  image: postgres:14.0
  database:
    size: 500Mi
    storageClassName: cstor-csi
  customConfig: authentik-postgres-conf
  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-postgres-secret
          key: superUserPassword
    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-postgres-secret
          key: replicationUserPassword
    - name: POSTGRES_MY_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-postgres-secret
          key: myDbPasword
