---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flame-config
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "ceph-block"
