---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - error-pages
  - cloudflare-ddns
  - external-dns
  - external-services
  - ingress-nginx
  - k8s-gateway
  - traefik
