---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: collab
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nextcloud.github.io/helm
      chart: nextcloud
      version: 2.10.0
      sourceRef:
        kind: HelmRepository
        name: nextcloud-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nextcloud
      tag: "23.0.0"

    persistence:
      enabled: true
      existingClaim: nextcloud-main
      nextcloudData:
        enabled: true
        existingClaim: nextcloud-data

    ingress:
      enabled: true
      className: "traefik"
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "cloud"
        hajimari.io/appName: "Nextcloud"
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: collab-nextcloud-dav-redirect@kubernetescrd,collab-hsts@kubernetescrd
      tls:
        - secretName: "${SECRET_DOMAIN/./-}-tls"
          hosts:
            - cloud.${SECRET_DOMAIN}

    nextcloud:
      host: cloud.${SECRET_DOMAIN}
      username: ${SECRET_NEXTCLOUD_ADMIN_USER}
      password: ${SECRET_NEXTCLOUD_ADMIN_PASSWORD}
      extraEnv:
        - name: TZ
          value: "${CONFIG_TZ}"
      phpConfigs:
        uploadLimit.ini: |
          upload_max_filesize = 16G
          post_max_size = 16G
          max_input_time = 3600
          max_execution_time = 3600
      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'overwrite.cli.url' => 'https://cloud.${SECRET_DOMAIN}',
            'overwriteprotocol' => 'https',
            'trusted_proxies' =>
              array(
                0 => '${NETWORK_K8S_CLUSTER_CIDR}',
                1 => '${NETWORK_K8S_CLUSTER_IPV6_CIDR}',
              )
          );
        phone_region.config.php: |-
          <?php
          $CONFIG = array (
            'default_phone_region' => 'NL',
            'defaultapp' => 'files'
          );
      mail:
        enabled: true
        fromAddress: no-reply
        domain: ${SECRET_DOMAIN}
        smtp:
          host: ${SECRET_SMTP_HOST}
          secure: tls
          authtype: LOGIN
          port: 587
          name: ${SECRET_SMTP_USERNAME}
          password: ${SECRET_SMTP_PASSWORD}

    internalDatabase:
      enabled: false

    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud-postgres.collab.svc.cluster.local:5432
      user: nextcloud
      password: ${SECRET_NEXTCLOUD_POSTGRES_PASSWORD}
      database: nextcloud

    cronjob:
      enabled: true

    redis:
      enabled: true
      usePassword: true
      password: ${SECRET_NEXTCLOUD_REDIS_PASSWORD}
