---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grocy
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: grocy
      version: 8.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/grocy
      tag: version-v3.1.2
      pullPolicy: IfNotPresent

    env:
      TZ: "${CONFIG_TZ}"
      GROCY_CULTURE: "nl"
      GROCY_CURRENCY: "EUR"

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/target: "dyn.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cart-variant"
          hajimari.io/appName: "Grocy"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "grocy.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "${SECRET_DOMAIN/./-}-tls"
            hosts:
              - "grocy.${SECRET_DOMAIN}"

    persistence:
      config:
        enabled: true
        storageClass: "ceph-block"
        accessMode: ReadWriteOnce
        size: 5Gi
