# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    HOME_IPV6_RANGE: ENC[AES256_GCM,data:Rc3tUVJ/xjr6W4u52UpwaUP0QNZa,iv:1YSDUNB0pvG1ZGHwSUwQntEJ3txAuv40UiuiQkQoZ7E=,tag:v0xDTQQL0ataVYb7b4lu5w==,type:str]
    PURELB_TRAEFIK_IPV6_ADDR: ENC[AES256_GCM,data:1LCiSGPUah3LhFW1vq566w0lwwt0,iv:I/6wZe8DgULd1Us4iBD8S86IPE6IybaPcjtWO0jLXqw=,tag:lEdENSMDLM+TFltLrUGUSA==,type:str]
    PURELB_IPV6_RANGE: ENC[AES256_GCM,data:JrHi6ZWnoXZ6/gz5JgQuzg+l8FZAcbMXlIUzEfbMrkTQYPC5yuqPW52Lkno6ww==,iv:dp7/cnX22iEiBXwkxSiGy1q8OZiwerDfwJv0q3PV8KU=,tag:qC/PfsiXHzl5nFSCa8A+gQ==,type:str]
    PURELB_MEMBERLIST_SECRET_KEY: ENC[AES256_GCM,data:ToFZ6Ps2i/HPyx8LUan2L1dRIJh/yWDiTjqxXGZY2mMdHGhJVQjOisBSLw==,iv:d5J7TwldQ4yQJDH/I3ZauKsvRAZ6HVCUhMAX/3cYC1w=,tag:piMX6X/rsFmasTpeCi0tYA==,type:str]
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:bkzIgQC5EsvhYCyE6V2GFhfQ2KoGQWZ3qL5R29JMPl7grkMOLszJyfqPSCZCg+80M1CKoiQqHavIL8ZKbW3/tVdwbGg=,iv:pRACHVW34OQz+TQ/Gguyl3v14GsK1IDGsWcIr+54dow=,tag:jm+8xd+yjhOR9bjtWeSXZg==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:Dt7eUP3kStVLdg4M3Uk86i0YyknOQeTyiw/tZTteBvcFzD1heknYFgxFiG0=,iv:B/oApUQioXzCvE/jfuzer957856ZewGHLisVZbFs/ys=,tag:cGY8kD4XnMY4KRve8ppEdw==,type:str]
    SECRET_AUTHENTIK_REDIS_PASSWORD: ENC[AES256_GCM,data:A5fYk7Li8AqniSKz6utWxPU28l4diV6AQRMv0Ggqaq6DL/XFj//D2B+7q8g=,iv:GwWbBV/KYNv52GiOOmJAOcWvY7p0ygm0lYY9VHABZdU=,tag:/1SoF3Hvu/Clt1ZWPam8ZA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:TKCITMI2guQ7+HNlXYdbIbR3rJwW6SMw,iv:NRAVVBazeCkn96ifLAuMWwHljebqVtub+bJr92fKYAI=,tag:gZLZzqLqgzwKg2+SqQ+ZeA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZLrNuStOQ8Ge0LM=,iv:7emRuXU0wyMWhzB0+VToh85akzZrUz0BLxPSzcVri/E=,tag:BiwmXvMxYEsOXsRckx31YA==,type:str]
    SECRET_EAB_KID: ENC[AES256_GCM,data:/+rvGdfE3LvavfGjHvSTg0c2ScB0tw==,iv:74F0zlcP/5mRy8ZRxzriG/tvmjXThMSxxBzsj1rZuYA=,tag:oYTmHWXv8JRSowj+z38UbQ==,type:str]
    SECRET_GHOST_MYSQL_PASSWORD: ENC[AES256_GCM,data:vpnavOOQjgnIrqXGF7dYC0iugSUDv3BhlN12crpcCZwvOr4m16ksZ5aQfxk=,iv:KECG4OR83jmfwOAT55RvLn3lVFV0gu0zQYuRyovh/E8=,tag:pxyMd3GVqlrNy4k+Qin/pw==,type:str]
    SECRET_MYSQL_OPERATOR_PASSWORD: ENC[AES256_GCM,data:uL8FpVBAOLwUGvg2UZ236Dko6II1UL0g4J8LWFsDyA3k30BdcRK0KMUNClU=,iv:VwS9XNS+Am2z3/g5QXQ68h3VMkHp1Chyl0mXDGCYdiE=,tag:ISWLS5HK3hR7MvOBk1Fw8g==,type:str]
    SECRET_NEXTCLOUD_POSTGRES_PASSWORD: ENC[AES256_GCM,data:5RAbw9LbIYCk/uc535FvHglil82UK05oyxaYavrs9PmTczWAEvXuYWZDmR8=,iv:sRUozXeDTKeGSFFReUDKAtn2dU3YP7ns6vRaKuS7xt8=,tag:j585ENlGEL49vaYJ0DvJzQ==,type:str]
    SECRET_NEXTCLOUD_REDIS_PASSWORD: ENC[AES256_GCM,data:+NO7E6vJFkHCrj8tD4gp0SObOxcMGHq8VpaesJaIzScAWgH9M/rJdD2QNI0=,iv:aUPgSyg49OO4IqQTvsMAmlGAU1CtfMBXR7Pl6gBGG2Y=,tag:SGTHqfaWDejqnq/pw6BHMQ==,type:str]
    SECRET_SMTP_HOST: ENC[AES256_GCM,data:ZDgabb+uXmXmCyVOeC/kIQ==,iv:6RW0yVn7P2ZGhyV9VcBZbcN+JU4g3VWjzuGmN7Qk9Kk=,tag:IokCBz36ex7wTZkrGJbhLw==,type:str]
    SECRET_SMTP_FROM: ENC[AES256_GCM,data:WqR9RqWyDSZQAsZ6dwMysswosQA=,iv:wZLc8c84rhmLgLHVv2Q/uvYl7TD16xsuT3eOYk5Qxr0=,tag:Qsrkk1k6USbUVxpMSP76EQ==,type:str]
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:/tJ3i9xstqPjVnW4T3uripZKmxWAKHE=,iv:szvKQlu6uCeiyHOAGFf3cK0lzKApX37BX8G+DDeSQfA=,tag:6bYC9WM69N7AxWnPoCaBfw==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:ZwAlV7mGDKn5JEPgzTOr4bf/eA==,iv:qUbr1EG2yRv4xRzyUJjAu7Umvd+yImv/WALxkNGy/9k=,tag:7Zt+MTzfg0K1FhZXp5KKeg==,type:str]
    SECRET_WIKIJS_POSTGRES_PASSWORD: ENC[AES256_GCM,data:RN8WyDzYPx2/WFCiU+y6eaRnjPkM+mXgpIM42WNUObyBh0XiQIvvzCuhVuE=,iv:ITISDsCiAwuaU5yEUFtaKj0Du6T6MNpmpJf4nG5o+AY=,tag:KaMD5/eJyj+qDbrqozkWfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yj38cqvxadheycx8tt5yxk8stt6l9cf5s3e6wd743752nr70d9zq99tna0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6a25sb2R5Tk5oOWQydHNt
            VkRJSjlaR09aVzI2QjljaUZvVlNaNXhlL0JrCk8vNEtHb1cvekFVVkdIL2RJekZ2
            TVFVYmFIV3FZOEJsSWI4KzBZNEtHUm8KLS0tIGhVUGU4UlZFSElwU0tKcjArQWMy
            MTdBaUVYN2x4Z3hzZ0RmNkJUcXhxbGcKADav9xKD9mVAb5Md83S8KBxdjPQM+1Ka
            VoYfW5t27MQE1Y+NPZpm87GJ/W5VOhWb/mhB/OS3F71N2x3bxSdWeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-21T00:43:30Z"
    mac: ENC[AES256_GCM,data:gdP00Jc3gI2b7wDg0MqeBywCX+l3cwYiwkAjuwBNdww+9610Dw5KIgUNo07Yhp1jYYoXdu86YAb364+fZISldCyek78pQ6MMmQk1UBaPFwIYfk/q0y+O3Iu/I7K/2JbXhUYvAYMWL8ljU0Jf0Kwb+yU7ZgFPvwj2O09EV0JOjCo=,iv:4ZL8R9m3p0613xbkhFj4YVtIt++4GHqj0gxU5vNqbb8=,tag:cwpLlH1BdyZfUF8KTh5uPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
