# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    METALLB_TRAEFIK_IPV6_ADDR: ENC[AES256_GCM,data:SVlyFLYaJ1PWwFyXj7RoAHsJAiG7,iv:FiPu4tDqW9LaEZ2HD9yntKiFSLrIpQp6ehK0nIFB/Wg=,tag:wYqMzyGYSsUvgIPnBwjPbw==,type:str]
    METALLB_LB_IPV6_RANGE: ENC[AES256_GCM,data:x1yglS8ucJME5zk/drg8hrS+amXKZGlYdGEk04x43L0xTvSjPzBoeB56hdZdsw==,iv:r64Q2MQ7hCfN77eLWkTsbklYwwuPZ8emoK7VboT6hFY=,tag:TPgWEvv0fS9GwE55AYb7uw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Vp9mGDU+J4J6q88=,iv:L++Kstdy7t8M7RwGRHdGmxHi0qfb/s4cruc1slSDYA8=,tag:ehdOEIGokddP4VMP5XuDWw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:5djs3iJHf8Ti9HBZOH97jTlct1U7iyBz,iv:XwoPwzIFvIJWyNtqQDPBfe+lYM6v5MaoPAJ3cw0YkSk=,tag:UJQjwmEACUUhpQTdmJU9oA==,type:str]
    SECRET_EAB_KID: ENC[AES256_GCM,data:6+Ctqll7ZzvTZ8AhY0R0Jvvkcd7Y5g==,iv:LN2nK28fQt4t+aQ9oqBYscpm0higEDjDtrCgkp047kc=,tag:aH6EjcYWo9fQ7xZOOY/L3w==,type:str]
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:eo5hVxzfOq2w5LbphvQ9sdGv+D23HtaY/+sTRxmOV4CokCujfjd3Oiej5YLmaRIrlEgH+xd8DaeiCMF2+Yg5fFEERDA=,iv:AB6GyjYaT7YJjH28yffHdqrIq+Z/AJmW819jCRxxM60=,tag:7VTUoQgjjOefLuqxpuzhrw==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:hiwwkRT0CuSfiehJdwGT2FOEsgaw7k684kFUPxqSGFibRjep8tFXEU8Yn+A=,iv:ej1kL/5duH7geFfOC51mY1nQF4aDv54WO34D58II/0M=,tag:5FVU4enVp7oCYRQUkkyi3g==,type:str]
    SECRET_AUTHENTIK_REDIS_PASSWORD: ENC[AES256_GCM,data:XARYb1aIpH3F9E+mObnzoW6mnjHNOiVHx6jB7BA3qs4uzbMx76F2AqDv9ZY=,iv:6BLdvE1nqRtmyN0+Q9S7TdZICX4FuNhHs/KzhhD9Ghs=,tag:7eF5haDoTrZYaUY3mYAoCg==,type:str]
    SECRET_NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:C1pqFvc=,iv:3ouX3FMDVoXGZwTYW9g7nVwZDuIz1lV1xTwjoDUGmIU=,tag:EgKC+o6IRq1i+C29gw7BLg==,type:str]
    SECRET_NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:B0QRQSPz0qkOjysqnY2OBTi6qR5PS42X0nnrUFpYsf7slOtblm426RsFFw==,iv:Ban1GnrulW4MyLebJWaj9hoW+wvdZ7s9fJDPgEwQEJ4=,tag:up1owEddqCrGMb3zA6GPSg==,type:str]
    SECRET_NEXTCLOUD_POSTGRES_PASSWORD: ENC[AES256_GCM,data:1D5u3t44uDKiwAIc4U5nebyKypYk3vTN2OnPCIUfmcczKIpRXfUoTfGnVWU=,iv:8t15XoE8s3+o3bPCoKn2LyhrNkhpBIUlOcfc4GHXoQ4=,tag:U8ow/VcykvACtD6ROZEU4w==,type:str]
    SECRET_NEXTCLOUD_REDIS_PASSWORD: ENC[AES256_GCM,data:L0t6hR2yCfgR/76VE/zUzBGOeXBR9VHmy7/VuRrAXnFQmpLIthkopy6kEwE=,iv:1H1gfCK6clGfF7UWPBSi+JCfRmU1ZBFWsFHTHWQwpgg=,tag:2McjLypmYHesH2fMeiR5DA==,type:str]
    SECRET_SMTP_HOST: ENC[AES256_GCM,data:VVDDjhzdwyK4Ey/3hk7MWg==,iv:tqyxcZ9uRAolNPUVNneK5Kbl9vQmi4gqfkpbNfPhgz8=,tag:NmS8clmBnkMvHCBR67NfoQ==,type:str]
    SECRET_SMTP_FROM: ENC[AES256_GCM,data:y8D4+3o7t/1VquhKr1pXjDEwm/I=,iv:IMF3s3lmJ9EYP9TDevMaomf9QC0fmBo+iLs0LOeeKFM=,tag:k+pTGsYAuzf81+nIrwbQrg==,type:str]
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:wORzNudYZ9FKkRKSB/rnDE6dfuErqYY=,iv:pzyxY/KU5PfNZ8ESpTHLilSh7Kj7OYb99wgR1SFMiTw=,tag:lUyWQOQjnt+WVu2MmSQjHA==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:+EQ0mnAHFsYfBwsNI5ttOVRnTg==,iv:6WerIG93eML4FeJeXezCUyfPmHD+mVdnuJzM1FdRvGw=,tag:GvYEal+LNW73AVtUda57CA==,type:str]
    SECRET_WIKIJS_POSTGRES_PASSWORD: ENC[AES256_GCM,data:Gt77WPUMncNSKYspY94nCw6xpRYcdOXXcv5W40ljSeRfwvHFR8NlWbpTuqI=,iv:0wxQJGfFNDgd78FeQD1Z59JCDfmc54tz8fE3nIsxY6s=,tag:Ri2VtYCgrqvXWXGrKGjEYw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yj38cqvxadheycx8tt5yxk8stt6l9cf5s3e6wd743752nr70d9zq99tna0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdUZQcy9QRXBTRWhnOURq
            MnNqcFZsUDM0TTR4TVpWbzl6ZGFUNVdGZ2tZCkdBV2pHYWJzZ1ZXbEdjc0lQa3or
            S2JZT2MzUW4wL3FFSThVT2lwZEs3dlUKLS0tIDM3RTZ5R1l3cHBQTnZEMGc3SHdt
            cWxnUExRRHo3TWVORjI5ZHVndlE5ZTgKhCZBRQQtJKD++PJnq6Ray64xgzHBpUC5
            ZHg6mVexv2LHsJRQcjk6W9mHqVY3aBzCf592EKWO1aNSEI+M2h+A9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-10-21T20:04:57Z"
    mac: ENC[AES256_GCM,data:TdvTo9J1L1xrZxXFclv0Rebm0G7zSMw3YEYEJ8RrEv2s32YX13FPWGa2XNe6+cmBWQxsQgp1/dQeq0igR0BtHBy1/+GbtOItvBeuneF3yQg9V6kb3RegHP/j2jqPx1ZjhZPdXc9CzZ6tx+exl1Yax2MJ+qQWp9+vHiFlHL6vtGo=,iv:hMvGZ9YfyzitObQhJcuY+asqC0ekZEJNEXbMsMwG7pk=,tag:CxN4DgIVEw4fs9WqhUdN8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
