# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    METALLB_TRAEFIK_IPV6_ADDR: ENC[AES256_GCM,data:Ubxnr0T+ZZITn8q8dU4YMlPdcI7u,iv:dPwRWuH3GO02NpbpkTPhshGfuYk/OnKF/fyaS5UC+Mk=,tag:rtgn/VRKjKHYSzNdl0d1rg==,type:str]
    METALLB_LB_IPV6_RANGE: ENC[AES256_GCM,data:HlRTP9si8N/xgurotMMQgKknpFzRP7vhTKCFKSJdItdtzVTjZtn6bfcQqS+Npts=,iv:VTEcrCUf9/h9peG5z/24WmykES/Xolhm2z3uIp5I8kw=,tag:IdHQqyD1LTTGhLKAoGT14w==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:BlRfi6Xk6o1hZ5w=,iv:kbwNV33Bagw1PMlzTQTgmatCP73bYEqEIHjoo1Dk2IY=,tag:YecYLpIKnrYZK1wej+HvtQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:wMsaRLzG1CkJCVn5FDjtLWu1DJLqsvge,iv:JF5Az4qQMFh07o8ZxcMrAJtely5zO6V95XSraNLoQkQ=,tag:kRPokOriADQIeKfA632jwQ==,type:str]
    SECRET_EAB_KID: ENC[AES256_GCM,data:uK9xit5exUPwaJdmBels8eBmi1IMdA==,iv:dMFkN0KK/w2T6JXeLScbFycV8h8j2ZLwbBJwuDrvOy8=,tag:G4I1uJ//iTezQFsyEU5zJQ==,type:str]
    SECRET_AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:FGE5BmdKvM+cxvQPXXzbB96bDtSehBqK1UkjJS8uX2rS5WFDqb3gwi1pYnNMEL6VrQwsXV60hBm3BOjUHmRZFLbrriI=,iv:kiGGkExazLrViqZtkiUGjmzcDwXYVBwb6oYcUDP6bDU=,tag:kGKanM2Frj1XfpUfAa7DTg==,type:str]
    SECRET_AUTHENTIK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:ZV4oaQGDeVzPmLTEJJD1oL857vni1qHdVZej6P24aRXgbDCosYhRioMOS8E=,iv:HSGI5CZ3nVgdf0qAfsTK2sAezRHJLsE1FLzcCsmhiY8=,tag:oo7ogfkTv7UfXqx402ZdvA==,type:str]
    SECRET_AUTHENTIK_REDIS_PASSWORD: ENC[AES256_GCM,data:l/Lw5B/A+0z0/vHVh3Ih15ZxZCDxnmL6hvag+iKjA5WQWGdo3I9BKtHQArA=,iv:KKvnLny6Kie6rFrXhjfFKPRvuYlChz5EGVjGbHhli6k=,tag:3oajMqsdUnrTwPbcMab/YQ==,type:str]
    SECRET_NEXTCLOUD_ADMIN_USER: ENC[AES256_GCM,data:Bbj7kTk=,iv:IxC2cIJozU+9UkgW9ikFtxeDeLRRdeZRFtWssyWFr7U=,tag:WFlskCgWk3gyBcOLlkjBrA==,type:str]
    SECRET_NEXTCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:id7mW/MEi3+jxmM30ZZPwZS/3/DqNdLb/JW07yObngt+tzVD2qQ1LBpT+A==,iv:9CZCVUotJxH5cQZ6N8MIPanwgFWlmiQiYqtPhrEqi60=,tag:3g5w0ndInJk6eJyH0RXJww==,type:str]
    SECRET_NEXTCLOUD_POSTGRES_PASSWORD: ENC[AES256_GCM,data:L86RqCGdxr8XTc3PD26cRvepvYn28uUaTTEOxv9WYLVtN2G5Q4SmodYbRsU=,iv:26ATz22GFatWKXWa3S+XTV/IadCbYoukop8JzPPByRk=,tag:UtbYW/d6x50J8GX6fboJIg==,type:str]
    SECRET_NEXTCLOUD_REDIS_PASSWORD: ENC[AES256_GCM,data:DOm2GaMWYS0fRN7uqL87Blo8tNcf6L4KnmOUmt6v7/GKT9IxC/ueDSKiW38=,iv:tRGuqTJmrmR3IWBLWjoVHqzeAmSgMr1dJrmqkYqcbQk=,tag:/e4naElqnVwiKUDjn1gRIA==,type:str]
    SECRET_SMTP_HOST: ENC[AES256_GCM,data:f8Gxp6j7LhUSDu0uWL+9kQ==,iv:rV0h2J7uN0sZVdoUHEler8vh3yIvqX+oS1jZZv34Wcc=,tag:n3D1ZgtfNQO5N2NvdDa8qg==,type:str]
    SECRET_SMTP_FROM: ENC[AES256_GCM,data:pB1rH7IVy7HCdhkiNpGeXCvxOfI=,iv:ljoOserfU9CSeVUABewi4sFYqYMCjbIeTZlLxpK9WDs=,tag:IkNcul1bq8KkPublj481JA==,type:str]
    SECRET_SMTP_USERNAME: ENC[AES256_GCM,data:o48iL7GWzopmMdQll6PRGGDXyzP6lQU=,iv:rLaKUOlIwg/Iq7ddRN7jVOSqPRrucuHCi+7caXb9JMs=,tag:mH5zs7D3yBCj2lWmq0mv7Q==,type:str]
    SECRET_SMTP_PASSWORD: ENC[AES256_GCM,data:Ga5pPG/2EIn1Yvv+AdZP+E/JrA==,iv:do2Vu1JDPGaHeSK4NNXx5CUiHwE+WgC035s+UxwQIqg=,tag:5WCKmgiVIN3IEYg6mVCW/w==,type:str]
    SECRET_WIKIJS_POSTGRES_PASSWORD: ENC[AES256_GCM,data:o650we0r1FPp9vbQmON3RD5ynGRSHu1DTNsnMXPOW3R96bv7weOczjOCXpo=,iv:7j60NhVjntQKMSX4Z5gdGqhHHlVwkv9Ej1cSIJMtaKY=,tag:Z3FjafEsjJDjr1h7SXQHWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yj38cqvxadheycx8tt5yxk8stt6l9cf5s3e6wd743752nr70d9zq99tna0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbHBxY2ZPT2xiTFVlMmw5
            MGdydGVYMDhKeEpaM09ZNXpLc2hLdUNCWngwCndmZlloalFQYTEzQmJKRTI5eGsx
            Y2J0NnB4ajIwYVBsbUZRUjdpK1pmY1kKLS0tIHcweHRCSENEVFI4SHhjTjRuR1FL
            QklDeS9mT2N3MkpadXdVMmgxeFREWDQKw6AeSq5JTYfHV/tdD4psxPMRtqOlgzV5
            BHDR82gg5VdKXpSLkf8ekx83eUkjnKKVnYuqZxApbd22IIpdF4YAPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-10-20T17:27:10Z"
    mac: ENC[AES256_GCM,data:Sdlr/5q5vQ5grmca67zfchePNnIXBPy9rbDXA0cbcWkZSx2VtyqaNOUOYR6QGDWaTbIQzcJKovTJEM7Vhelwd99Eoq0gJeN/TsWoEHfc9EEDQqlrfiZuc2AUG2ZZUXgdAb0thOrLXaRPbbzBwJxjYoN8DuTQyY1qGr/BnvsYTGI=,iv:yT/WXL1YC8i5Tu5j1yLeRCFD5oopuc44TMKDmSp/xoI=,tag:QAHxG2F8gNlh5L2WlQjHuw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
