---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monica-db
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "openebs-jiva-csi-default"