---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monica
  namespace: default
spec:
  releaseName: monica
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: monica
      version: 6.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: monica
      tag: 3.4.0-apache
    
    env:
      TZ: "${CONFIG_TZ}"
      APP_ENV: production
      DB_HOST: monica-mariadb
      DB_DATABASE: monica
      DB_USERNAME: monica
      DEFAULT_MAX_STORAGE_SIZE: 4096
      APP_URL: https://monica.${SECRET_DOMAIN}
      APP_KEY: ${SECRET_MONICA_APP_KEY}
      DB_PASSWORD: ${SECRET_MONICA_DB_PASSWORD}
      MAIL_MAILER: smtp
      MAIL_HOST: ${SECRET_SMTP_HOST}
      MAIL_PORT: 587
      MAIL_USERNAME: ${SECRET_SMTP_USERNAME}
      MAIL_PASSWORD: ${SECRET_SMTP_PASSWORD}
      MAIL_ENCRYPTION: tls
      MAIL_FROM_ADDRESS: ${SECRET_SMTP_FROM}
      MAIL_FROM_NAME: Monica
    
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "account-group"
          hajimari.io/appName: "Monica"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "monica.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "${SECRET_DOMAIN/./-}-tls"
            hosts:
              - "monica.${SECRET_DOMAIN}"

    persistence:
      config:
        enabled: true
        storageClassName: "openebs-jiva-csi-default"
        size: 2Gi

    mariadb:
      enabled: true
      auth:
        database: monica
        username: monica
        password: ${SECRET_MONICA_DB_PASSWORD}
        rootPassword: ${SECRET_MONICA_ROOT_PASSWORD}
      primary:
        persistence:
          enabled: true
          storageClassName: "openebs-jiva-csi-default"
