---
apiVersion: v1
kind: Pod
metadata:
  name: disk-wipe-hydra
spec:
  restartPolicy: Never
  nodeName: hydra
  containers:
    - name: disk-wipe
      image: busybox
      securityContext:
        privileged: true
      command:
        [
          "/bin/sh",
          "-c",
          "dd if=/dev/zero bs=1M count=10000 oflag=direct of=/dev/sdb"
        ]
