---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flame
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    fullnameOverride: flame
    image:
      repository: docker.io/pawelmalak/flame
      tag: 2.3.0
    env:
      TZ: "${CONFIG_TZ}"
      PASSWORD: "${SECRET_FLAME_PASSWORD}"
    service:
      main:
        ports:
          http:
            port: 5005
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns.alpha.kubernetes.io/target: "dyn.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: &host "flame.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: flame-config
        mountPath: /app/data
    serviceAccount:
      name: flame
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi