---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flame
  namespace: default
  labels:
    app.kubernetes.io/name: flame
    app.kubernetes.io/instance: flame
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flame
  labels:
    app.kubernetes.io/name: flame
    app.kubernetes.io/instance: flame
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flame
  labels:
    app.kubernetes.io/name: flame
    app.kubernetes.io/instance: flame
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flame
subjects:
- kind: ServiceAccount
  name: flame
  namespace: default