# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: flame-secrets
    namespace: default
stringData:
    password: ENC[AES256_GCM,data:7yWzrsVVE9cMpBCm,iv:pd5u9oPVOX/iWMtPaEmZ5JYjSBBzY5v9PJu+xeCnDL0=,tag:ICM0W4WnwbEnH0XAiE6Nkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yj38cqvxadheycx8tt5yxk8stt6l9cf5s3e6wd743752nr70d9zq99tna0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dVYzWkVESVhycUJUTi9u
            UmExOVdhRkRXL1RldWJMSERjbFJ4OXBDMHhNCk5LNGZ1RjFxUXJPb281Vy9RRzJS
            b1BzaVZtMzN3bGRjcXRtcVFqV0ZlenMKLS0tIGdBa2NDbmhieXR4WTB5ZVoyUFkw
            RVAzQ2ZYUVBjWmVDU0liTzRGajRKOTQKpMqGEMymU3NFhXFYzI7YZNKKqqCDPkq1
            Nd7cUXsmMDj6dLXdUxnyOmPrfDc+dzBucNkK097vGKRfPXuuCKF+5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-17T21:56:33Z"
    mac: ENC[AES256_GCM,data:qGpvU0B/ZWVJjZdInFBSlklbItL3BnIxOa0DslaVBDbkZl/2t97r2IFlQ2ykY1M8NNKZDpipOU4wubAiIk6LuoVz12TYT9tqyR2+65j4Sli77ZFYRhbD5/wGtN9vgkk3dewlZUbuI8Q/EP2Co3FWqWFhHSi4u2GIzmaYww7Nm0I=,iv:R+BfHidaBy6JLbEq7ja3LwBe/Hlf0+kKcJcOPmvyyks=,tag:70faLJXz75q5qIFt+2+Oiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
