---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 10.13.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    image:
      name: ghcr.io/k8s-at-home/traefik
    deployment:
      kind: Deployment
      replicas: 1
    service:
      enabled: true
      type: LoadBalancer
      spec:
        ipFamilyPolicy: PreferDualStack
        externalIPs:
          - "${PURELB_TRAEFIK_IPV4_ADDR}"
          - "${PURELB_TRAEFIK_IPV6_ADDR}"
        externalTrafficPolicy: Local
    logs:
      general:
        format: json
        level: INFO
      access:
        enabled: true
        format: json
        filters:
          statuscodes: "404,401,300-302"
    ingressClass:
      enabled: true
      isDefaultClass: true
      fallbackApiVersion: v1
    ingressRoute:
      dashboard:
        enabled: false
    globalArguments:
      - "--api.insecure=true"
      - "--serverstransport.insecureskipverify=true"
      - "--providers.kubernetesingress.ingressclass=traefik"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"
    additionalArguments:
      - "--providers.kubernetesingress.ingressendpoint.ip=${PURELB_TRAEFIK_IPV4_ADDR}"
      - "--providers.kubernetesingress.ingressendpoint.ip=${PURELB_TRAEFIK_IPV6_ADDR}"
      - "--providers.kubernetesingress.allowexternalnameservices=true"
      - "--providers.kubernetescrd.allowexternalnameservices=true"
    ports:
      traefik:
        expose: true
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
          options: "default"
      metrics:
        port: 8082
        expose: true
        exposedPort: 8082
    tlsOptions:
      default:
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
        cipherSuites:
          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 # TLS 1.2
          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 # TLS 1.2
          - TLS_AES_256_GCM_SHA384 # TLS 1.3
          - TLS_CHACHA20_POLY1305_SHA256 # TLS 1.3
        curvePreferences:
          - CurveP521
          - CurveP384
        sniStrict: true
    pilot:
      enabled: false
    experimental:
      plugins:
        enabled: false
    resources:
      requests:
        memory: 100Mi
        cpu: 500m
      limits:
        memory: 500Mi
