---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre-web
      version: 8.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/linuxserver/calibre-web
      tag: version-0.6.13
    env:
      TZ: "${CONFIG_TZ}"
      PUID: 1001
      PGID: 1001
      DOCKER_MODS: "linuxserver/calibre-web:calibre|ghcr.io/gilbn/theme.park:calibre-web"
      TP_THEME: "plex"
    persistence:
      config:
        enabled: true
        existingClaim: calibre-web-config
        mountpath: /config
      books:
        enabled: true
        existingClaim: calibre-web-books
        mountPath: /books
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: "dyn.${SECRET_DOMAIN}"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          hajimari.io/enable: "true"
          hajimari.io/icon: "bookshelf"
        hosts:
        - host: "books.${SECRET_DOMAIN}"
          paths:
          - path: /
        tls:
        - hosts:
          - "books.${SECRET_DOMAIN}"
    resources:
      requests:
        memory: 256Mi
    probes:
      startup:
        spec:
          periodSeconds: 15