---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    meta.helm.sh/release-name: tigera-operator
    meta.helm.sh/release-namespace: tigera-operator
  labels:
    app.kubernetes.io/managed-by: Helm
  name: tigera-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: tigera-operator
    meta.helm.sh/release-namespace: tigera-operator
  labels:
    app.kubernetes.io/managed-by: Helm
  name: tigera-operator
  namespace: tigera-operator
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    meta.helm.sh/release-name: tigera-operator
    meta.helm.sh/release-namespace: tigera-operator
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
  labels:
    app.kubernetes.io/managed-by: Helm
  name: tigera-operator
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  hostIPC: false
  hostNetwork: true
  hostPID: false
  hostPorts:
  - max: 65535
    min: 0
  privileged: false
  readOnlyRootFilesystem: false
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - hostPath
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: tigera-operator
    meta.helm.sh/release-namespace: tigera-operator
  labels:
    app.kubernetes.io/managed-by: Helm
  name: tigera-operator
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - podtemplates
  - services
  - endpoints
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - update
  - delete
  - watch
- apiGroups:
  - ""
  resources:
  - resourcequotas
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ""
  resourceNames:
  - calico-critical-pods
  - tigera-critical-pods
  resources:
  - resourcequotas
  verbs:
  - create
  - get
  - list
  - update
  - delete
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - patch
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - rolebindings
  - roles
  verbs:
  - create
  - get
  - list
  - update
  - delete
  - watch
  - bind
  - escalate
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - delete
  - watch
- apiGroups:
  - apps
  resourceNames:
  - tigera-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - operator.tigera.io
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - update
  - patch
  - delete
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - update
  - delete
  - get
  - list
  - watch
- apiGroups:
  - crd.projectcalico.org
  resources:
  - felixconfigurations
  verbs:
  - create
  - patch
  - list
  - get
  - watch
- apiGroups:
  - crd.projectcalico.org
  resources:
  - ippools
  - kubecontrollersconfigurations
  - bgpconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scheduling.k8s.io
  resources:
  - priorityclasses
  verbs:
  - create
  - get
  - list
  - update
  - delete
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - get
  - list
  - update
  - delete
  - watch
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - list
  - watch
  - create
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
  - delete
  - watch
- apiGroups:
  - policy
  resourceNames:
  - tigera-operator
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: tigera-operator
    meta.helm.sh/release-namespace: tigera-operator
  labels:
    app.kubernetes.io/managed-by: Helm
  name: tigera-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tigera-operator
subjects:
- kind: ServiceAccount
  name: tigera-operator
  namespace: tigera-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: tigera-operator
    meta.helm.sh/release-namespace: tigera-operator
  labels:
    app.kubernetes.io/managed-by: Helm
    k8s-app: tigera-operator
  name: tigera-operator
  namespace: tigera-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
      name: tigera-operator
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: tigera-operator
        meta.helm.sh/release-namespace: tigera-operator
      labels:
        app.kubernetes.io/managed-by: Helm
        k8s-app: tigera-operator
        name: tigera-operator
    spec:
      containers:
      - command:
        - operator
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: tigera-operator
        - name: TIGERA_OPERATOR_INIT_IMAGE_VERSION
          value: v1.27.7
        envFrom:
        - configMapRef:
            name: kubernetes-services-endpoint
            optional: true
        image: quay.io/tigera/operator:v1.27.7
        imagePullPolicy: IfNotPresent
        name: tigera-operator
        volumeMounts:
        - mountPath: /var/lib/calico
          name: var-lib-calico
          readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: tigera-operator
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      volumes:
      - hostPath:
          path: /var/lib/calico
        name: var-lib-calico
---
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  annotations:
    meta.helm.sh/release-name: tigera-operator
    meta.helm.sh/release-namespace: tigera-operator
  labels:
    app.kubernetes.io/managed-by: Helm
  name: default
spec: {}
---
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  annotations:
    meta.helm.sh/release-name: tigera-operator
    meta.helm.sh/release-namespace: tigera-operator
  labels:
    app.kubernetes.io/managed-by: Helm
  name: default
spec:
  calicoNetwork:
    ipPools:
    - blockSize: 26
      cidr: 10.244.0.0/16
      encapsulation: None
      natOutgoing: Enabled
      nodeSelector: all()
    - blockSize: 120
      cidr: fd12:3456:789a:244::/56
      encapsulation: None
      natOutgoing: Enabled
      nodeSelector: all()
  imagePullSecrets: []
  kubernetesProvider: ""
  nodeMetricsPort: 9091
  typhaMetricsPort: 9093
