---
installation:
  enabled: true
  calicoNetwork:
    ipPools:
      - blockSize: 26
        cidr: "10.244.0.0/16"
        encapsulation: "None"
        natOutgoing: Enabled
        nodeSelector: all()
      - blockSize: 120
        cidr: "fd12:3456:789a:244::/56"
        encapsulation: "None"
        natOutgoing: Enabled
        nodeSelector: all()
  nodeMetricsPort: 9091
  typhaMetricsPort: 9093

apiServer:
  enabled: true
