---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: miniflux
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: miniflux
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/linuxserver/freshrss
      tag: version-1.18.1
      pullPolicy: IfNotPresent

    env:
      TZ: "${TIMEZONE}"

    persistence:
      config:
        enabled: true
        storageClass: "ceph-block"
        accessMode: ReadWriteOnce
        size: 5Gi

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "dyn.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "rss-box"
          hajimari.io/appName: "FreshRSS"
        hosts:
          - host: "rss.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "${SECRET_DOMAIN/./-}-tls"
            hosts:
              - "rss.${SECRET_DOMAIN}"

    resources:
      requests:
        cpu: 75m
        memory: 64Mi
      limits:
        memory: 128Mi
