---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  values:
    persistence:
      # workaround for https://github.com/longhorn/longhorn/issues/2964
      defaultFsType: ext4
      defaultClassReplicaCount: 1
      defaultClass: true
      reclaimPolicy: Retain
    defaultSettings:
      defaultDataPath: /longhorn
      defaultDataLocality: "best-effort"
      defaultReplicaCount: 1
      volumeAttachmentRecoveryPolicy: immediate
    env:
      TZ: "${CONFIG_TZ}"
    ingress:
      enabled: true
      ingressClassName: "traefik"
      host: "longhorn.${SECRET_DOMAIN}"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
      tls: true
      tlsSecret: "${SECRET_DOMAIN/./-}-tls"
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
