---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: freshrss
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: freshrss
      version: 6.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/linuxserver/freshrss
      tag: version-1.18.1
      pullPolicy: IfNotPresent

    env:
      TZ: "${CONFIG_TZ}"

    persistence:
      config:
        enabled: true
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 5Gi

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "rss-box"
          hajimari.io/appName: "FreshRSS"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "rss.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: "${SECRET_DOMAIN/./-}-tls"
            hosts:
              - "rss.${SECRET_DOMAIN}"

    resources:
      requests:
        cpu: 75m
        memory: 64Mi
      limits:
        memory: 128Mi
