---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - calico-system
  - collab
  - database
  - default
  - flux-system
  - home
  - kube-system
  - networking
  - security
  - tigera-operator
