---
apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
  name: cstor-storage
  namespace: openebs
spec:
  pools:
    - nodeSelector:
        kubernetes.io/hostname: hydra
      dataRaidGroups:
        - blockDevices:
            - blockDeviceName: blockdevice-961b503d56ae5c13ae34d3b6c35ac06e
      poolConfig:
        dataRaidGroupType: stripe