---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cstor
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://openebs.github.io/cstor-operators
      chart: cstor
      version: 3.0.1
      sourceRef:
        kind: HelmRepository
        name: cstor-charts
        namespace: flux-system
      interval: 10m
  values:
    # Required when using the same device that hosts the OS FS partition
    openebs-ndm:
      ndm:
        sparse:
          count: '1'