# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    namespace: cert-manager
    name: eab-secret
data:
    secret: ENC[AES256_GCM,data:WY3D4kG7zQNbnMh6DugU3GUSFp4Mi2p+uVu6h1QfQ5jJGMRvUWGn0KZfSf1sAwq1DcwVPfJ/jvj2tiQUOUJoNWrjyJju08KTUWNus+lqx2huhvXvLy1tJVtRIIFoFrCdZHm4C3gzw3CTvB6wLkaUsGWuNS4=,iv:sjtgdfhNvsCdISauVHTZUxH+EnmzZydABFu4mTTAZvI=,tag:qzyZgfzlyGJWGZJSOFh/wA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yj38cqvxadheycx8tt5yxk8stt6l9cf5s3e6wd743752nr70d9zq99tna0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOFdnRFQ5dHV1STUxdG5k
            NThxc3Btd0QzUW1rY2VhWng5ZXpFbWhrRnpJCitMM0c1OXVqY0JVb1RTTEN6U0Ix
            WHdJOUNIMWRaMk5JeXFLR1RYVUZ5Z28KLS0tIDZVSWhKZ1paRmVxUU8rN2U2TWx2
            OUl6aEdCYWwvL210RGFPTWF6Y0pFOUUK1GfbxsYom9ucJYaHMz0XtAUrITjd+YPd
            pjFUs8GuCtFC+xBdjKv825NlSAX2IupF9LofXtqUMAHVbsX1Sw3vZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-24T22:27:14Z"
    mac: ENC[AES256_GCM,data:aY3Fq6W1d6oA404GDNqa98qe1JGLRR384Sn5/7ct1LDRtvrfMvnAzq2SRomKkv85c5EXOIQ+I4oQJd3snq21w2a2UVaZz9CD6A3WkVdYC/VY7hDgGVNHsNLOaMIx5GZIgTnK5c83RanNBFZ2TwrDDIsrv0s8X6odOifajGv3QeE=,iv:jxAMMIKYd2cE/VDAIEvpmhGQaORxJEDDrfEDTRgVWks=,tag:cceml5gLLkAcMn/Is+x92Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
