# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    namespace: cert-manager
    name: eab-secret
data:
    secret: ENC[AES256_GCM,data:yyqWhVvqK9iytoql5X+N3YNhOx9v/8rjOqwILCF6HfOZlxgPUCvKk+3p8UUMDo/Znh1MJ4n2nNoD8lT/pM+7QAz2GB8euNqRbwDzauCqr5UQXZvqPQolM522TTbLNPR24kybJyd6GHrYdrSoYGqfTXEa5Rs=,iv:QY4mW+3ddiy0vuIZ0R5tuxYF/eoaDWxKb/CMvGs0Fmw=,tag:9R3jim1CEJwTwxOaLyf3QQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yj38cqvxadheycx8tt5yxk8stt6l9cf5s3e6wd743752nr70d9zq99tna0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOFdnRFQ5dHV1STUxdG5k
            NThxc3Btd0QzUW1rY2VhWng5ZXpFbWhrRnpJCitMM0c1OXVqY0JVb1RTTEN6U0Ix
            WHdJOUNIMWRaMk5JeXFLR1RYVUZ5Z28KLS0tIDZVSWhKZ1paRmVxUU8rN2U2TWx2
            OUl6aEdCYWwvL210RGFPTWF6Y0pFOUUK1GfbxsYom9ucJYaHMz0XtAUrITjd+YPd
            pjFUs8GuCtFC+xBdjKv825NlSAX2IupF9LofXtqUMAHVbsX1Sw3vZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-15T22:52:44Z"
    mac: ENC[AES256_GCM,data:aRLriPULwBc03kRCoek3dJC/tNBytjX5286Sgn3zkIIIVHxIBwJydxm0VaZmgj0kY2uE2dvq81JMF1Y3nHITZ6jl7bIEOdPidU7S7HwfR7sM8u7sYkiDLWzLXNiDGBJc3aaBxuH03M6P/Uk7liEpFRgqVJJPQAQjUGw8v8LEw44=,iv:PHOmUo6uCJ0fPJhWENohyjGMi0k19uLwcInI+EUQ2pI=,tag:CTgakd4OUAolTBPFE/MCUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
