---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl-production
spec:
  acme:
    email: ${SECRET_CLOUDFLARE_EMAIL}
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: ${SECRET_EAB_KID}
      keySecretRef:
        name: eab-secret
        key: secret
    privateKeySecretRef:
      name: zerossl-production
    solvers:
      - dns01:
          cloudflare:
            email: "${SECRET_CLOUDFLARE_EMAIL}"
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
