---
name: Schedule - Update Flux

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  flux-upgrade:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: "${{ secrets.APP_ID }}"
          private_key: "${{ secrets.APP_PRIVATE_KEY }}"
      - name: Install Flux
        uses: fluxcd/flux2/action@main
      - name: Flux Update
        id: update
        run: |
          CLI_VERSION="$(flux -v)"
          VERSION="v${CLI_VERSION#*flux version }"
          flux install --version="${VERSION}" \
            --components-extra=image-reflector-controller,image-automation-controller \
            --network-policy=false \
            --export > ./cluster/base/flux-system/gotk-components.yaml
          echo "::set-output name=flux_version::$VERSION"
      - name: Create pull request for Flux upgrade
        uses: peter-evans/create-pull-request@v3
        with:
          token: "${{ steps.generate-token.outputs.token }}"
          branch: "github-action/flux-update-${{ steps.update.outputs.flux_version }}"
          delete-branch: true
          title: "chore(github-action): update flux components to ${{ steps.update.outputs.flux_version }}"
          signoff: true
          commit-message: "chore(github-action): update flux components to ${{ steps.update.outputs.flux_version }}"
          body: |
            Release notes: https://github.com/fluxcd/flux2/releases/tag/${{ steps.update.outputs.flux_version }}
          labels: |
            renovate/github-action
