---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://hajimari.io
      chart: hajimari
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: hajimari-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/toboshii/hajimari
      tag: v0.1.0
    env:
      TZ: "${CONFIG_TZ}"
    hajimari:
      defaultEnable: false
      namespaceSelector:
        matchNames:
          - collab
          - default
          - home
          - monitoring
          - networking
          - security
      name: "David"
      groups:
        - name: Communicate
          links:
            - name: Discord
              url: "https://discord.com"
            - name: Outlook
              url: "https://outlook.com"
        - name: Cloud
          links:
            - name: Cloudflare
              url: "https://dash.cloudflare.com"
            - name: Onedrive
              url: "https://onedrive.com"
        - name: Dev
          links:
            - name: Codepen
              url: "https://codepen.io/"
            - name: Devdocs
              url: "https://devdocs.io"
            - name: Devhints
              url: "https://devhints.io"
        - name: Media
          links:
            - name: Deezer
              url: "https://deezer.com"
            - name: Trakt
              url: "https://trakt.tv"
            - name: YouTube
              url: "https://youtube.com/feed/subscriptions"
        - name: Reading
          links:
            - name: Medium
              url: "http://medium.com"
            - name: Reddit
              url: "http://reddit.com"
        - name: Tech
          links:
            - name: Hacker News
              url: "https://news.ycombinator.com/"
            - name: MIT Technology Review
              url: "https://www.technologyreview.com/"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "hajimari.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hajimari.${SECRET_DOMAIN}"
            secretName: "${SECRET_DOMAIN/./-}-tls"
    persistence:
      data:
        enabled: true
        existingClaim: hajimari-config
    resources:
      requests:
        cpu: 100m
        memory: 128M
